baseURL = "https://Gaby6333.github.io/notre-site/"
languageCode = "fr-ca"
title = "Nos aventures"
theme = "PaperMod"

[params]
  homeInfoParams = {Title = "Bienvenue 👋", Content = "Les aventures de Gaby et Léonie"}
  ShowCategories = true
  ShowTags = true
  ShowReadingTime = false

[taxonomies]
  category = "categories"
  tag = "tags"

[[menus.main]]
  identifier = "menu-activites"
  name = "Activités"
  url = "categories/activit%C3%A9s/"
  weight = 1

[[menus.main]]
  identifier = "menu-restos"
  name = "Restos"
  url = "categories/restos/"
  weight = 2

[[menus.main]]
  identifier = "menu-voyages"
  name = "Voyages"
  url = "categories/voyages/"
  weight = 3

[[menus.main]]
  identifier = "menu-quotidien"
  name = "Quotidien"
  url = "categories/quotidien/"
  weight = 4

[markup.goldmark.renderer]
  unsafe = true